
var allData = {peptideData: [{id: 0, peptideSequence: 'AAAA', modificationStates: [{id: 0,
                                                                          modDesc: '+1',
                                                                          mods: [{id: 0, position: [1], name: 'aAAA', 
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]},
                                                                                 {id: 1, position: [2], name: 'AaAA', 
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]},
                                                                                 {id: 2, position: [3], name: 'AAaA', 
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]},
                                                                                 {id: 3, position: [4], name: 'AAAa',
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]}]},
                                                                         {id: 1,
                                                                          modDesc: '+3',
                                                                          mods: [{id: 0, position: [2,3,4], name: 'Aaaa', 
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]},
                                                                                 {id: 1, position: [1,3,4], name: 'aAaa', 
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]},
                                                                                 {id: 2, position: [1,2,4], name: 'aaAa', 
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]},
                                                                                 {id: 3, position: [1,2,3], name: 'aaaA', 
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]}]}]},
                   {id: 1, peptideSequence: 'CCCC', modificationStates: [{id: 0,
                                                                          modDesc: '+1',
                                                                          mods: [{id: 0, position: [1], name: 'cCCC', 
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]},
                                                                                 {id: 1, position: [2], name: 'CcCC', 
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]},
                                                                                 {id: 2, position: [3], name: 'CCcC', 
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]},
                                                                                 {id: 3, position: [4], name: 'CCCc', 
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]}]},
                                                                         {id: 1,
                                                                          modDesc: '+3',
                                                                          mods: [{id: 0, position: [2,3,4], name: 'Cccc',
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]},
                                                                                 {id: 1, position: [1,3,4], name: 'cCcc', 
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]},
                                                                                 {id: 2, position: [1,2,4], name: 'ccCc',
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]},
                                                                                 {id: 3, position: [1,2,3], name: 'cccC',
                                                                                  matchData: [{id: 0, mz: 0.999999, name: 'match1.1', ionType: 'b', ionPosition: 3},
                                                                                              {id: 1, mz: 1.000001, name: 'match1.2', ionType: 'b', ionPosition: 3},
                                                                                              {id: 2, mz: 1.000002, name: 'match1.3', ionType: 'b', ionPosition: 3},
                                                                                              {id: 3, mz: 2.000001, name: 'match2.1', ionType: 'b', ionPosition: 4},
                                                                                              {id: 4, mz: 2.000002, name: 'match2.2', ionType: 'b', ionPosition: 4},
                                                                                              {id: 5, mz: 3.200000, name: 'match3.1', ionType: 'b', ionPosition: 5}]}]}]}],
fullTestData: [{ proteinName: "protein1",
                      proteinId: 0,
                      peptides: [{ peptideId: 0,
                                   peptideDataId: 0,
                                   modificationStateId: 0,
                                   scans: [{ scanNumber: 101,
                                             scanId: 0,
                                             chargeState: 1,
                                             precursorScanData: [{mz: 1, into: 1},
                                                                 {mz: 1.5, into: 1.5},
                                                                 {mz: 2.0078, into: 2}],
                                             precursorMz: 1,
                                             quantScanData: [{mz: 1, into: 1},
                                                             {mz: 1.5, into: 1.5},
                                                             {mz: 2, into: 2}],
                                             quantMz: [1, 2], 
                                             choiceData: [{modsId: 0, state: "accept"},
                                                          {modsId: 1, state: "maybe"},
                                                          {modsId: 2, state: "reject"},
                                                          {modsId: 3, state: null}],  
                                             scanData: [{mz: 1, into: 15, matchInfo: [{modsId: 0, matchId: 2},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 2, into: 20, matchInfo: [{modsId: 0, matchId: 3},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 3, into: 25, matchInfo: [{modsId: 0, matchId: 5},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 4, into: 30, matchInfo: [{modsId: 0, matchId: null},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]}]
                                           },
                                           { scanNumber: 103,
                                             scanId: 1,
                                             chargeState: 2,
                                             precursorScanData: [{mz: 1, into: 1},
                                                                 {mz: 1.504, into: 1.5},
                                                                 {mz: 2.0078, into: 2}],
                                             precursorMz: 1,
                                             quantScanData: [{mz: 1, into: 1},
                                                             {mz: 1.5, into: 1.5},
                                                             {mz: 2, into: 2}],
                                             quantMz: [1, 2],   
                                             choiceData: [{modsId: 0, state: "accept"},
                                                          {modsId: 1, state: "maybe"},
                                                          {modsId: 2, state: "reject"},
                                                          {modsId: 3, state: null}],  
                                             scanData: [{mz: 1, into: 1, matchInfo: [{modsId: 0, matchId: 2},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 2, into: 5, matchInfo: [{modsId: 0, matchId: 3},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 3, into: 5, matchInfo: [{modsId: 0, matchId: 5},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 4, into: 5, matchInfo: [{modsId: 0, matchId: null},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]}]
                                           }]
                                 },
                                 { peptideId: 1,
                                   peptideDataId: 0,
                                   modificationStateId: 1,
                                   scans: [{ scanNumber: 102,
                                             scanId: 0,
                                             chargeState: 1,
                                             precursorScanData: [{mz: 1, into: 1},
                                                                 {mz: 1.5, into: 1.5},
                                                                 {mz: 2.0078, into: 2}],
                                             precursorMz: 1,
                                             quantScanData: [{mz: 1, into: 1},
                                                             {mz: 1.5, into: 1.5},
                                                             {mz: 2, into: 2}],
                                             quantMz: [1, 2],   
                                             choiceData: [{modsId: 0, state: "accept"},
                                                          {modsId: 1, state: "maybe"},
                                                          {modsId: 2, state: "reject"},
                                                          {modsId: 3, state: null}],  
                                             scanData: [{mz: 1, into: 15, matchInfo: [{modsId: 0, matchId: 2},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 2, into: 20, matchInfo: [{modsId: 0, matchId: 3},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 3, into: 25, matchInfo: [{modsId: 0, matchId: 5},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 4, into: 30, matchInfo: [{modsId: 0, matchId: null},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]}]
                                           },
                                           { scanNumber: 104,
                                             scanId: 1,
                                             chargeState: 1,
                                             precursorScanData: [{mz: 1, into: 1},
                                                                 {mz: 1.5, into: 1.5},
                                                                 {mz: 2.0078, into: 2}],
                                             precursorMz: 1,
                                             quantScanData: [{mz: 1, into: 1},
                                                             {mz: 1.5, into: 1.5},
                                                             {mz: 2, into: 2}],
                                             quantMz: [1, 2],   
                                             choiceData: [{modsId: 0, state: "accept"},
                                                          {modsId: 1, state: "maybe"},
                                                          {modsId: 2, state: "reject"},
                                                          {modsId: 3, state: null}],  
                                             scanData: [{mz: 1, into: 15, matchInfo: [{modsId: 0, matchId: 2},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 2, into: 20, matchInfo: [{modsId: 0, matchId: 3},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 3, into: 25, matchInfo: [{modsId: 0, matchId: 5},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 4, into: 30, matchInfo: [{modsId: 0, matchId: null},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]}]
                                           }]
                                 },
                                 { peptideId: 2,
                                   peptideDataId: 1,
                                   modificationStateId: 0,
                                   scans: [{ scanNumber: 103,
                                             scanId: 0,
                                             chargeState: 1,
                                             precursorScanData: [{mz: 1, into: 1},
                                                                 {mz: 1.5, into: 1.5},
                                                                 {mz: 2.0078, into: 2}],
                                             precursorMz: 1,
                                             quantScanData: [{mz: 1, into: 1},
                                                             {mz: 1.5, into: 1.5},
                                                             {mz: 2, into: 2}],
                                             quantMz: [1, 2],   
                                             choiceData: [{modsId: 0, state: "accept"},
                                                          {modsId: 1, state: "maybe"},
                                                          {modsId: 2, state: "reject"},
                                                          {modsId: 3, state: null}],  
                                             scanData: [{mz: 1, into: 15, matchInfo: [{modsId: 0, matchId: 2},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 2, into: 20, matchInfo: [{modsId: 0, matchId: 3},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 3, into: 25, matchInfo: [{modsId: 0, matchId: 5},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]},
                                                        {mz: 4, into: 30, matchInfo: [{modsId: 0, matchId: null},
                                                                                      {modsId: 1, matchId: null},
                                                                                      {modsId: 2, matchId: null},
                                                                                      {modsId: 3, matchId: null}]}]
                                           }]
                                 }]
                    }]
}

